### PR TITLE
Support sentinel-based ranges in default stringify

### PR DESCRIPTION
**Pull request by seanmiddleditch**
Fix for issue #2003 

- Enhances `rangeToString` to work with a separate iterator and sentinel type
- Adds a test to ensure this compiles

### CODE REVIEW

**Comment by horenmar** [comment]
Tests in default run cannot fail, or it will fail CI. Instead, you should use `::Catch::Detail::stringify` in the test and check that the return value matches expected stringification.

**Comment by seanmiddleditch** [comment]
Ah, didn't expect the tests to fail, actually. Looking it over though it makes sense, though I'm not sure why I didn't experience that locally.

**Comment by seanmiddleditch** [comment]
@horenmar - I'm not familiar with the approval test stuff here; should I be checking in the files that are modified locally on build?

**Comment by horenmar** [comment]
On a second look, this part seems to be missing [from the documentation](https://github.com/catchorg/Catch2/blob/master/docs/contributing.md#testing-your-changes) after the rewrite. 🤔 

Approval tests diff known good output with current output. If there are changes, check that the diff makes sense, run `scripts/approve.py` and commit the updated baselines.

**Comment by horenmar** [comment]
Looks good now, thanks.

**Pull request merged**
