### PR TITLE
Add AllTrue, AnyTrue, NoneTrue generic range matchers

### PR DESCRIPTION
**Pull request by schallerr**
## Description
This PR adds `AllTrue`, `AnyTrue`, `NoneTrue` generic range matchers, which match a range if all, any, or none of the elements in a range are `true`, respectively.

## GitHub Issues
Addresses issue #2109.

### CODE REVIEW

**Comment by urielgarciarivas** [comment]
Closes #2136.

**Comment by johnbeard** [comment]
If I could rebase this and include the (All|Any|None)True matchers in the now-existing src/catch2/matchers/catch_matchers_quantifiers.hpp(since 57c8036a9914811c56ab07852f231a36e97b0ded), would that work? Or should they be implemented differently?

**Comment by inductiveload** [comment]
Actually, I clearly misread that diff - the rebase is just .gitignore and the acceptance tests. Is there anything else here that I could improve to drive this forward - these matchers would be useful to me.

**Comment by johnbeard** [comment]
Actually, clearly I misread the diff - the only rebase needed here was in .gitignore and the approval test counts: https://github.com/johnbeard/Catch2/tree/matchers_all_any_none_true

Is there anything else I can do here to drive this forward? Merging these matchers would be useful to me.

**Comment by horenmar** [comment]
@johnbeard If you split out the test refactoring to separate PR and then a separate PR for the new functionality, I will review both.

**Comment by schallerr** [comment]
I split out the test refactoring to #2386. I'll rebase this PR once the other one is merged.

**Pull request merged**
