### PR TITLE
Make CATCH_BREAK_INTO_DEBUGGER be user-configurable

### PR DESCRIPTION
**Pull request by khyperia**
Unfortunately, the project I work on supports platforms under NDA, and so I can't upstream the fixes here.

(It'd be really nice if all platform configuration macros like this were externally configurable! But just this one is the one we need right now.)

### CODE REVIEW

**Comment by khyperia** [comment]
The test failure is `Error: retrieving gpg key timed out.`, not sure how to retrigger tests

**Comment by horenmar** [comment]
AFAIK only accounts with access to the repo are allowed to rerun Travis tests.

Anyway, the change looks reasonable enough, but I'd like to also see it added to the documentation. (See `docs/contributing.md` how to properly add a "introduced in" placeholder)

**Comment by khyperia** [comment]
Let me know if that's what you were thinking of with documentation!

**Comment by horenmar** [comment]
Thanks. The documentation was good enough but I noticed that it was a subheading of "Disabling Exceptions", so I pulled it out and rewrote slightly.

**Pull request merged**
