### PR TITLE
fix: `TEST_DL_PATHS` to multi-args

### LINKED ISSUE #2736: catch_discover_tests() DL_PATHS can't handle two or more paths
**Describe the bug**
I am trying to specify shared libs paths to tests. It was fine for 1 library to add it to `DL_PATHS` of `catch_discover_tests()`, but adding more paths has no effect.
```cmake
catch_discover_tests(Tests
    DL_PATHS
        "${path_to_A}/lib"
        "${path_to_B}/lib"  # test executable won't use it
)
```

I understood it with some tricky logic:
- Library `A` is 3rd party and no such on system.
- Library `B` is 3rd party too, but system has it analog with a little changed functionality (say older version). So without providing path `B` my executable runs, but fails internally.

When running `ctest --verbose` I saw:
```
...
1: Working Directory: C:/Users/Administrator/Project/build
1: Environment variable modifications:
1:  PATH=path_list_prepend:C:\Users\Administrator\Project\build\path\to\A\lib 
...
```
see only one lib in `PATH`, but `DL_PATHS` provided with 2.

**Expected behavior**

Test executable would have `PATH` prefixed with all paths provided in `DL_PATHS` parameter of `catch_discover_tests()`

**Reproduction steps**
You can try having small repro with such 

```cmake
enable_testing()

include(FetchContent)
FetchContent_Declare(
    Catch2
    GIT_REPOSITORY https://github.com/catchorg/Catch2.git
    GIT_PROGRESS TRUE
    GIT_SHALLOW TRUE
    GIT_TAG v3.4.0 # I used this version
)
FetchContent_MakeAvailable(Catch2)

# define test executable and link shared/imported libs
...


catch_discover_tests(Tests
    EXTRA_ARGS ${TEST_ARGS}
    DL_PATHS
        "$Env{PATH}"
        "${path_to_A}/lib")
```
i.e. I added needed library after some placeholder. It won't work either

**Platform information:**

 - OS: Windows 10.0.20348.0
 - Compiler+version: **MSVC 17**  19.36.32532.0
 - Catch version: **v3.4.0**
 - cmake 3.26.4

**Additional context**
I see DL_PATHS passed somewhere on POST_BUILD branch:
```
-D "TEST_DL_PATHS=${_DL_PATHS}"
```

### PR DESCRIPTION
**Pull request by LecrisUT**
## Description
As @daniel-slater mentioned in #2736, the issue was that `TEST_DL_PATHS` in `CatchAddTests.cmake` should be a multi-argument variable. I have tested it against a generator-expression input like:
```cmake
	list(APPEND extra_args
			DL_PATHS "$<TARGET_RUNTIME_DLL_DIRS:test-suite>"
	)
```
[example_run](https://github.com/LecrisUT/CMake-Template/actions/runs/8047422750/job/21976647512?pr=12)

I did not add proper tests to check for this issue because I couldn't find any functional tests that run `ctest --build-and-test`, and that would require some discussion on how to structure and place these.

Also note that there is a much cleaner approach by automatically adding `TARGET_RUNTIME_DLL_DIRS`, which I will try to do in another PR.

## GitHub Issues
Closes #2736

### CODE REVIEW

**Comment by horenmar** [comment]
Re tests: I am not sure whether the DL_PATHS property shows up under `--show-only=json-v1`. If the answer is yes, then we can just inspect the CTest configuration to see whether there are indeed multiple dl paths shown.

There is already a test that configures build, runs `catch_discover_tests` and then inspects the output from ctest, in `tests/TestScripts/DiscoverTests/`. This could be slotted in there easily.

**Comment by LecrisUT** [comment]
> There is already a test that configures build, runs catch_discover_tests and then inspects the output from ctest, in tests/TestScripts/DiscoverTests/. This could be slotted in there easily.

Cool I can add the test-case there. By default I think it should be using 2 DLLs, unless we need to add a dummy library target. I think functional tests like that should use the built-in `ctest --build-and-test` since it can more easily forward the generator, compilers, etc. and does not require any installation of catch. A complex framework that can do all checks and everything would be how upstream CMake does it, but for this project a simple run and test ctest should be fine.

**Comment by horenmar** [comment]
I see you added the setting to the CMakeLists for the tests, but there is no check in the script that  runs the test. Do you intend to pursue this further?

**Comment by LecrisUT** [comment]
It is partly implicitly added, i.e. by `TARGET_RUNTIME_DLL_DIRS:tests` should contain the `DLL_DIRS` for `tests.exe` and `catch.dll`. I did not double-check this though, but if I am wrong, we can fix it by adding a dummy `lib.cpp` and library target to link it to where we put a simple `1+1=2` test or something.

**Pull request merged**
