### PR TITLE
New init / deinit listener methods

### PR DESCRIPTION
**Pull request by rcdailey**
Relates to #537

### CODE REVIEW

**Comment by rcdailey** [comment]
I decided to go ahead and create an init / deinit method pair, similar to the started/ended methods we currently have in reporters. This allows setup and teardown logic to occur per "leaf" test (could be a section or test case)

**Comment by rcdailey** [comment]
I amended a change that enables the `testStepDeinit()` method to be invoked when a test case throws an exception (utilizing an RAII object).

@philsquared I opened this 16 days ago and have continued to keep it updated. When can I expect someone to have time to get me some feedback and possibly merge the change?

**Comment by rcdailey** [comment]
@horenmar If maybe phil is not available, would you be able to contribute some feedback?

**Comment by rcdailey** [comment]
Thanks Phil, and again sorry to rush, I just wanted to make sure any major suggestions are made as early as possible so I can make any changes you need. I've written unit tests on my side to depend on these changes, so in order to avoid our code depending on it too long, I wanted to get it reviewed & merged with the final interface (if changes are needed).

I can be patient. Hopefully someone will have time for this soon. Thanks for replying back!

**Comment by onqtam** [comment]
Hi!

Isn't what you want already possible with ```testCaseStarting```/```sectionStarting``` and ```testCaseEnded```/```sectionEnded```?

Or if the test case related methods are called only once even for a test case with multiple sections - isn't that what the ```testGroupStarting```/```testGroupEnded``` are for?

Seems to me that the behavior you are looking for can be emulated in a custom reporter/listener with some custom logic and overriding these methods... Or perhaps I'm missing something.

**Comment by rcdailey** [comment]
@onqtam The way these various functions work makes sense from a reporting perspective, but to do any kind of functional (program-affecting) logic, they're not sufficient. My new methods utilize RAII to make sure the init happens prior to entering a test case, and that deinit happens after the closing scope of the test case. They enable you to do setup/tear-down logic at a global level in the window of time where no objects should be alive in any active test cases or sections. They also allow tear-down to happen when exceptions are thrown.

There were 2 main problems I couldn't solve with the existing reporter methods:

* Singletons could not be released between each test case or section
* Working directory files could not be deleted

To execute any of the above actions requires that no active objects in a test case or section be alive. You can't tear-down in `sectionEnded()`, for example, because this is executed prior to the test case scope ending (objects still alive at the test-case level) and you can't use `testCaseEnded()` because this is not executed more than once with 2 or more sections inside it.

**Comment by philsquared** [comment]
Sorry - been ultra busy for a while (again) - just finished with one (work) release, so have a brief moment of downtime - thanks for the ping offline...

There's a couple of ways you could achieve the same goal without changing anything.

1. You could keep a count of section nesting (++ in `sectionStarting`, -- in `sectionEnded`. Before and after, respectively, if you check for 0 you know you're dealing with the section call that corresponds to the test case.
2. You could use a(n old school) fixture class and do your init/ deinit in the ctor/ dtor of that.

If necessary I could maybe add a flag to `SectionInfo` that indicates if it's for a `TEST_CASE` or not, so you could check that.

Give that we already make a reporter/ listener call for this event (`sectionStarting`/`Ended`) I'd rather not add an extra one - especially given there are a couple of ways to do it that aren't too burdensome. I admit the first option is a little less obvious - but the second one, at least, seems to be the right fit?

**Comment by rcdailey** [comment]
Do you have an example of the fixture class? I'm not understanding how that
fixes the issue.

**Comment by rcdailey** [comment]
@philsquared Ping? Right now I'm doing your 1st suggestion:

```
void GlobalStateCleanup::sectionStarting(Catch::SectionInfo const& _sectionInfo)
{
   ++m_sectionDepth;
}

void GlobalStateCleanup::sectionEnded(Catch::SectionStats const&)
{
   if (m_sectionDepth > 0 && --m_sectionDepth == 0)
   {
      DeleteGlobalState();
   }
}
```

While this is simple enough, I'd still like to see a code example of the fixture class you were talking about. I've never done that in Catch and not familiar with it.

**Comment by philsquared** [comment]
You are correct that it requires all test cases that you want to partake in the common setup/ teardown to use `TEST_CASE_METHOD`. I can see that retrofitting that might not be optimal - so I think the `sectionEnded()` technique with the  `m_sectionDepth` trick is probably the best workaround.

I don't think this is a common enough need to add an extra pair of handlers to every reporter, so I'm reluctant to do that, given that the workaround is ok. Are you satisfied with that approach?

**Comment by rcdailey** [comment]
I'm starting to realize this doesn't solve my problem. Basically, my code change addresses cleanup at the leaf-section level, whereas this solution only does the cleanup after the root section (the test case). If I have a test case with 3 sections inside of it, I need all 3 sections inside to get cleaned up, but the outer test case (or even intermediate sections) do not need cleanup since they would have already been cleaned up by the nested section. Does this make sense?

**Comment by philsquared** [comment]
I'm afraid I'm not quite following. Perhaps you could sketch a simple outline example we could talk about in more concrete terms?

**Comment by philsquared** [comment]
(FTR, AFAICS, the `m_sectionDepth` trick should give you the same semantic as your proposed init/deinit methods)

**Comment by rcdailey** [comment]
The more I'm thinking about this, I think the more I might be getting confused. Let me write an MCVE and get back with you

**Comment by rcdailey** [comment]
Ok you're right, this is the same. Here's a live sample:
https://wandbox.org/permlink/b8XwAfXxopzhU6Fw

This code:

```cpp
class GlobalStateCleanup : public Catch::TestEventListenerBase
{
public:

    // Inherit constructor
    using TestEventListenerBase::TestEventListenerBase;

    void sectionStarting(Catch::SectionInfo const&) override
    {
        ++m_sectionDepth;
    }

    void sectionEnded(Catch::SectionStats const&) override
    {
        if (m_sectionDepth > 0 && --m_sectionDepth == 0)
        {
            DeleteGlobalState();
        }
    }

private:

    void DeleteGlobalState()
    {
        std::cout << "Global State Deleted\n";
    }

    unsigned m_sectionDepth{};
};

CATCH_REGISTER_LISTENER(GlobalStateCleanup)

TEST_CASE("Root Test", "[test]")
{
    std::cout << "Begin Test Case\n";
    
    SECTION("Section One")
    {
        std::cout << "Section One\n";
    }
    
    SECTION("Section Two")
    {
        std::cout << "Section Two\n";
    }
    
    std::cout << "End Test Case\n";
}
```
Yields this output:

```
Begin Test Case
Section One
End Test Case
Global State Deleted
Begin Test Case
Section Two
End Test Case
Global State Deleted
===============================================================================
test cases: 1 | 1 passed
assertions: - none -
```

Would it be useful to create a generic Listener for this in contrib? Basically something like:

```cpp

class GlobalStateCleanup : public Catch::TestEventListenerBase
{
public:

    // Inherit constructor
    using TestEventListenerBase::TestEventListenerBase;
    
    virtual void initTest(Catch::SectionInfo const&) {}
    virtual void deinitTest(Catch::SectionStats const&) {}

private:

    void sectionStarting(Catch::SectionInfo const& info) final
    {
        if (m_sectionDepth++ == 0)
        {
            initTest(info);
        }
    }

    void sectionEnded(Catch::SectionStats const& stats) final
    {
        if (m_sectionDepth > 0 && --m_sectionDepth == 0)
        {
            deinitTest(stats);
        }
    }

    unsigned m_sectionDepth{};
};
```

That way anyone that wants to do this only has to implement `GlobalStateCleanup` and implement either of `initTest()` and `deinitTest()`? If you think it's a good idea, maybe help me figure out some better names and I'm happy to open a new PR. Thanks @philsquared !!

**Comment by rcdailey** [comment]
Better example:

```cpp
class TestInitDeinitListener : public Catch::TestEventListenerBase
{
public:

    using TestEventListenerBase::TestEventListenerBase;
    
    virtual void initTest(Catch::SectionInfo const&) {}
    virtual void deinitTest(Catch::SectionStats const&) {}

private:

    void sectionStarting(Catch::SectionInfo const& info) final
    {
        if (m_sectionDepth++ == 0)
        {
            initTest(info);
        }
    }

    void sectionEnded(Catch::SectionStats const& stats) final
    {
        if (m_sectionDepth > 0 && --m_sectionDepth == 0)
        {
            deinitTest(stats);
        }
    }

    unsigned m_sectionDepth{};
};

class GlobalStateCleanup : public TestInitDeinitListener
{
public:

    using TestInitDeinitListener::TestInitDeinitListener;
    
    virtual void initTest(Catch::SectionInfo const&)
    {
        std::cout << "Init Test\n";
    }
    
    virtual void deinitTest(Catch::SectionStats const&)
    {
        std::cout << "Deinit Test\n";
    }
};

CATCH_REGISTER_LISTENER(GlobalStateCleanup)
```

**Pull request closed without merging**
