### PR TITLE
test: add bazel build rule for SelfTest

### PR DESCRIPTION
**Pull request by c8ef**
## Description

This PR primarily accomplishes two tasks:

1. It adds `MODULE.bazel.lock` to the `.gitignore` file.
2. It includes a Bazel build rule for SelfTest, which can be utilized with the command `bazel test //tests:catch2_self_test`.

### CODE REVIEW

**Comment by horenmar** [comment]
What's the advantage of having SelfTest build rule in repo, when the main development is done using CMake?

**Comment by c8ef** [comment]
There may not be much advantage, but I noticed the meson build file for the test case. I believe it would be beneficial to have a corresponding Bazel build rule for those using Bazel.

**Comment by horenmar** [comment]
Fair enough.

**Comment by c8ef** [comment]
Thanks!

**Pull request merged**
