### PR TITLE
Add example code linked to from documentation, part 1

### PR DESCRIPTION
**Pull request by martinmoene**
PR linked to issue #1037.

I've integrated building of the examples into CMake.

**`USE_EXAMPLES`**&emsp;The examples are built if `USE_EXAMPLES` is `true`. This name follows the existing pattern, but may not properly reflect the choice. `NO_EXAMPLES` is the wrong way round. Plain `EXAMPLES` is weird.
Do you have suggestions?

**Travis, AppVeyor**&emsp; I've not touched CI yet. Do you have suggestions here; I wouldn't mind to leave this to experts.

Other remarks?

### CODE REVIEW

**Comment by martinmoene** [comment]
Should we perhaps use `NO_SELFTEST` on the build with examples, as the selftest has already been created for that confiuration?

**Comment by horenmar** [comment]
> Do you have suggestions?

`BUILD_EXAMPLES`?

> Do you have suggestions here; I wouldn't mind to leave this to experts.

Not sure where we are going to get them 😄 , but for Travis, we already specify all elements of the build matrix explicitly, so we can just add new one:
```yaml
    - os: linux
      compiler: gcc
      addons: *gcc6
      env: COMPILER='g++-6' BUILD_TYPE='Debug' CPP14=1 EXAMPLES=1
```
and change the build line:
```yaml
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Wdev -DUSE_CPP11=${CPP11} -DUSE_CPP14=${CPP14} -DBUILD_EXAMPLES=${EXAMPLES}
```
I don't think we need to build the examples with all compilers and configurations, as SelfTest should catch bugs, we just want the examples to not get out of date.


AppVeyor would be a bit harder, but I think we can specify explicit inclusion for the build matrix similarly:
```yaml
matrix:
    include:
        -
            Examples: 1
            os: Visual Studio 2015
        -
            Examples: 1
            os: Visual Studio 2013
```
and change the `before_build` lines similarly.

**Comment by martinmoene** [comment]
To promote the desired use of Catch with separate compilation of Catch itself and the tests in one or more other source files, I'm considering to apply that idiom to all tests with a common main (e.g. 000-CatchMain.cpp) except for  examples 010-TestCase.cpp (single file usage) and 020-TestCase,-[12].cpp (multiple files usage).

Would that be a good idea?

**Comment by martinmoene** [comment]
>Looking through or travis config, we should do some cleanup there. CPP11 toggle is no longer relevant, as that is the base assumption.

Perhaps not slip this in this subject's PR.

**Comment by horenmar** [comment]
@martinmoene The cleanup is done, but you will likely need to rebase.

**Comment by horenmar** [comment]
Keeping the number of separately compiled mains down is a good idea, they take quite a long time to compile. The fact that it teaches good practices is a nice bonus.

**Comment by martinmoene** [comment]
@horenmar File `210-Evt-EventListeners.cpp` fails to compile without `CATCH_CONFIG_MAIN`:
```
../examples/210-Evt-EventListeners.cpp:70:81: error: 'Catch::TestRunInfo' has not been declared
```
Same holds for other listener-related types.

Did I miss something?

**Comment by horenmar** [comment]
@MartinMoene Listeners and reporters require `CATCH_CONFIG_EXTERNAL_INTERFACES` to be defined. It is implied by both `RUNNER` and `MAIN`, which is why it works. It should be in the docs :smile:

**Comment by martinmoene** [comment]
It _is_ in the docs (blush).

**Comment by martinmoene** [comment]
@horenmar 

Up to now I've got:
- several examples that are linked to from the documentation
- examples/CMakeLists.txt mentioned in ./CMakeLists.txt
- integration with Travis
- initial integration with AppVeyor

I could use some help with the latter.

I tried to compile examples only for a single configuration, but have not yet succeeded. Your suggestion does not work: `include` is not a valid word to use there.

**Comment by horenmar** [comment]
@martinmoene Yeah, I've noticed so. It is in Travis, so I just assumed it would work.

I'll take a look at AppVeyor (hopefully soon)

**Comment by martinmoene** [comment]
@horenmar I've been able to limit building of examples to Win32 and x64, Release only. I've (silently) removed the exclusion phrase for VS2013.

What's next: offer a squashed PR for examples, part1?

**Comment by horenmar** [comment]
Pretty much

**Comment by martinmoene** [comment]
Squashed, ready to be merged.

**Comment by horenmar** [comment]
Looks good to me. I might rejigger the CI matrix afterwards, I have some further changes planned :smile:

**Comment by martinmoene** [comment]
Thanks!

**Pull request merged**
