### PR TITLE
[Please review, don't merge] Add examples

### PR DESCRIPTION
**Pull request by martinmoene**
Hi,

Per issue #1037 I've added folder examples, docs/list-of-example.md and a small subset of the example mentioned there.

I'd like to know if this PR represents a sane direction, or if there are any other remarks you'd like to make.

Thanks in advance.

### CODE REVIEW

**Comment by horenmar** [comment]
Looks reasonable enough so far, but I also remember you wanting to make compiling and running these part of CI. Are you still planning to do so?

**Comment by martinmoene** [comment]
Yeah, I'll have a look at compiling as part of CI shortly; I'm not so sure about running though.

**Comment by philsquared** [comment]
Argh, sorry! I always forget that deleting a branch closes all associated issues and PRs - with no way to re-open :-(

**Comment by philsquared** [comment]
How much of this is still outstanding? I know you've been working through it.

**Comment by martinmoene** [comment]
I think it's perfectly fine to have this one closed.

I had started to look at integrating compilation of the examples with CI, but got stuck on how to approach that in face of what's already there (and got sidetracked by other things).

Further, (many) more examples must be created and locations found to link to them.

A question is: should all examples be added at one time, or can it be done incrementally (once building them is integrated)?

**Comment by horenmar** [comment]
@martinmoene It is ok to add them incrementally. As to building them, I suggest creating a standalone CMakeLists that defines all targets for the examples and then (conditionally) including it from the main CMakeLists.

Also, note that they should not be built as part of normal development build, but should be hidden behind a CI specific option (we already do that for C++14, so you can just copy that).

**Comment by martinmoene** [comment]
@horenmar Thanks for the pointers.

**Pull request closed without merging**
