### PR TITLE
Examples: Add semicolon after INFO

### PR DESCRIPTION
**Pull request by JoeyGrajciar**
Add semicolon after INFO in examples

### CODE REVIEW

**Comment by horenmar** [comment]
The change in `catch_capture.hpp` needs to wait for next major.

**Comment by JoeyGrajciar** [comment]
@horenmar without those change in catch_capture.hpp warning will not be suppressed in case of `INFO`. unless user explicitly uses the new suppression macro around such usages.

**Comment by horenmar** [comment]
Right, I only read the first two commits. I meant removing the semicolon from `INTERNAL_CATCH_INFO`.

**Comment by JoeyGrajciar** [comment]
I also meant that :) that will correctly fix the warning

**Pull request merged**
