### PR TITLE
Add directory to Translations to Portuguese [Incrementally]

### PR DESCRIPTION
**Pull request by pinho**
## Description

[Edited] I added a directory on docs called __ptbr__ to add the files translated from English. It may be used to provides documentation with dynamic language to external webpages, if need in the future.

My idea is to do it incrementally, until all translate files.

## GitHub Issues
 
I commented about this in Issue #1674 

## Translated files

- [X] tutorial.md
- [ ] assertions.md
- [ ] benchmarks.md
- [ ] ci-and-misc.md
- [ ] cmake-integration.md
- [ ] command-line.md
- [ ] commercial-users.md
- [ ] configuration.md
- [ ] deprecations.md
- [ ] event-listeners.md
- [ ] generators.md
- [ ] limitations.md
- [ ] list-of-examples.md
- [ ] logging.md
- [ ] matchers.md
- [ ] opensource-users.md
- [ ] other-macros.md
- [x] own-main.md
- [ ] release-notes.md
- [ ] release-process.md
- [ ] reporters.md
- [ ] slow-compiles.md
- [ ] test-cases-and-sections.md
- [ ] test-fixtures.md
- [ ] tostring.md
- [ ] why-catch.md

### CODE REVIEW

**Comment by horenmar** [comment]
As a small nitpick, I would prefer the subdirectories be named in locale style, that is `pt_BR`.

Before the end, you will also have to update the scripts that automatically update documentation links on release.

**Comment by ronaldpnh** [comment]
Ok. I'll take care for this. ;)

**Comment by claremacrae** [comment]
Hi, any thoughts about what will happen to existing links, bookmarks, references from other project's documentation, when the existing English Markdown pages get moved to a sub-directory?

Could anything be done to prevent broken links? Does github allow redirects to be set up?

**Comment by ronaldpnh** [comment]
> Hi, any thoughts about what will happen to existing links, bookmarks, references from other project's documentation, when the existing English Markdown pages get moved to a sub-directory?
> 
> Could anything be done to prevent broken links? Does GitHub allow redirects to be set up?

Hello! I removed the subdirectory for English documentation. Let all markdown files in docs directory and i created a pt_BR directory for docs translated, justly to keep the links on the original files.

I don't know well about links management in markdown files on the Github.
Some projects uses a subdirectory for each language, but generally, the content of the files is used by webpages (see about [Brython](https://brython.info/) project and it [structure on Github](https://github.com/brython-dev/brython/tree/master/www/doc)). I believe this documentation type is usual.

**Pull request closed without merging**
